name: Selenium Java CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (Java Development Kit)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # You can choose your JDK distribution (e.g., adopt, zulu)
          java-version: '11'     # Specify the Java version needed for your project

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies and run tests
      - name: Run tests
        run: mvn clean test
